trigger:
  - master

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '>= 3.5' 
    addToPath: true 
    architecture: 'x64'

- script: |
    pip install -r requirements.txt
    pip install -e .
  condition: and(succeeded(), eq(variables['agent.os'], 'linux'))
  displayName: install aztk

- script: |
    pytest -n 50
  condition: and(succeeded(), in(variables['agent.os'], 'linux'))
  displayName: pytest
